### ISSUE TITLE
Function is implemented in mkdocs-material - feature: navigation.indexes

### ISSUE THREAD

**Issue by trasba** [oprypin/mkdocs-section-index#16]
ℹ️ 
I just came across this because I was looking for this functionallity.
However after going through the mkdocs-material documentation I believe this functinoallity is build into mkdocs-material.
Just activate it with:
```
  features:
  - navigation.indexes
```
See details here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
Or am I missing something?

**Comment by oprypin** [comment]
Yeah it's mostly the same functionality, with minor config differences.

This extension arrived sooner and aimed to support any interested theme. That theme's author chose to do the same thing separately.
