### ISSUE TITLE
Detect mkdocs-nature as supported theme

### ISSUE THREAD

**Issue by pawamoy** [oprypin/mkdocs-section-index#19]
[MkDocs-Nature](https://github.com/waylan/mkdocs-nature) seems to support section-index natively. Example: https://pawamoy.github.io/markdown/sitemap.html, built from https://github.com/pawamoy/markdown/tree/api-docs. It would be nice if it was detected as a supported theme, to get rid of the warning.

Possible solution (tested, seems to work fine) in `rewrites.py`:

```python
        if path.endswith("/mkdocs/templates/sitemap.xml"):
            src = _transform_mkdocs_sitemap_template(src)
        elif path.endswith("/nature/base.html"):
            self.found_supported_theme = True
            return src, filename, uptodate
        else:
            ...
```

Let me know if I should open a PR :slightly_smiling_face: 

A way to disable the warning would be fine too.

**Comment by oprypin** [comment]
:hushed: how did it happen that it supports that?

**Comment by oprypin** [comment]
https://github.com/waylan/mkdocs-nature/blob/cb23b75c8435d85c0027b0ce3d426fe17a66b673/nature/base.html#L6-L16 great stuff! :+1:  That's the way to go when writing a theme

We'll list it for sure

**Comment by oprypin** [comment]
Release in a day probably
