### ISSUE TITLE
Compatibility with Material for MkDocs "Navigation Tabs" feature

### ISSUE THREAD

**Issue by ZaLiTHkA** [oprypin/mkdocs-section-index#2]
For reference, the feature I'm referring to is documented here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs

I was _hoping_ with `navigation.tabs` enabled, that selecting a tab would show the contents of the relevant `index.md` file, but alas it does not.. When I remove that feature flag, then Section Index works perfectly.

---

Is this something that needs to change over here, or in the "Material for MkDocs" project?

**Comment by oprypin** [comment]
It works on latest master. You can use that now or wait a few days for a release.

**Comment by oprypin** [comment]
Released v0.2.2. This release is basically all about supporting this.

**Comment by ZaLiTHkA** [comment]
Awesome, thanks for the update. (:

**Comment by ZaLiTHkA** [comment]
..and just to follow up, `v0.2.2` does indeed play nicely with Material for MkDocs `navigation.tabs` feature. Thanks again. 👍
