### ISSUE TITLE
Doesn't support the "Instant loading" feature from Material for MkDocs

### ISSUE THREAD

**Issue by PegasisForever** [oprypin/mkdocs-section-index#3]
When [Instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading) is enabled, clicking on the section title still reloads the page.

**Comment by oprypin** [comment]
That is indeed true. Things still work but aren't instant.
Sorry to get back so late, I expected this issue to be much harder to solve.
But, solved it now. Will probably cut a release soon.
