### ISSUE TITLE
Plugin doesn't work properly with mkdocs-material 7.3.1

### ISSUE THREAD

**Issue by jaklan** [oprypin/mkdocs-section-index#7]
Issue was initially described in `mkdocs-material` repo, but as mentioned there - it should be solved on the plugin level:
https://github.com/squidfunk/mkdocs-material/issues/3072

**Comment by oprypin** [comment]
Thanks for the report.
This is fixed in https://github.com/oprypin/mkdocs-section-index/commit/f4b1e5bf53b04eb057f68511754e754c0f5e4295.
Will close this when I make a release.
