### ISSUE TITLE
Missing arrow for sections with one child

### ISSUE THREAD

**Issue by jaklan** [oprypin/mkdocs-section-index#9]
As below - even if there are sub-sections / sub-pages inside given section, the arrow is missing. I noticed it's related to the number of childs - if there are at least two, the arrow is there.

![image](https://user-images.githubusercontent.com/24907857/140258871-3f8f64a5-7c64-4935-bc28-a2c799059c0f.png)
-
![image](https://user-images.githubusercontent.com/24907857/140258595-ac2ae57c-03d8-451d-9871-fc6ffd44f144.png)

**Comment by oprypin** [comment]
Very sorry for the huge delay on this.

cc @Blacksmoke16
